# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSCRUD' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSCRUD
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'

  target 'iOSCRUDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSCRUDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
